# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      DETA_ACCESS_KEY: ${{ secrets.DETA_ACCESS_KEY }}
      DETA_PROJECT_KEY: ${{ secrets.DETA_PROJECT_KEY }}
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        curl -fsSL https://get.deta.dev/cli.sh | sh
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Update Environment Variables
      run: |
        echo DETA_PROJECT_KEY=$DETA_PROJECT_KEY >> .env
    - name: Linter
      run: |
        echo "Run Linter"
    - name: Unit tests
      run: |
        python -m pytest tests/unit/
    - name: Test deploy
      run: |
        uvicorn main:app --reload &
    - name: Integration test
      run: |
        python -m pytest tests/test_e2e.py
    - name: Deploy
      run: |
        ~/.deta/bin/deta clone --name corsica --project corsica tmp/
        cp -r tmp/.deta corsica/
        cp requirements.txt corsica/
        ~/.deta/bin/deta deploy corsica
