# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
    - name: Linter
      run: |
        echo "Run Linter"
    - name: Unit tests
      run: |
        poetry -vvv run pytest tests/unit/
    - name: Test deploy
      run: |
        uvicorn main:app --reload &
    - name: Integration test
      run: |
        poetry run pytest tests/test_e2e.py
